# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/darshith/hls/gemm/gemm_vivado/gemm_vivado.srcs/sources_1/bd/gemm/ip/gemm_axi_mem_intercon_imp_auto_pc_0/gemm_axi_mem_intercon_imp_auto_pc_0.xci
# IP: The module: 'gemm_axi_mem_intercon_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/darshith/hls/gemm/gemm_vivado/gemm_vivado.gen/sources_1/bd/gemm/ip/gemm_axi_mem_intercon_imp_auto_pc_0/gemm_axi_mem_intercon_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_axi_mem_intercon_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/darshith/hls/gemm/gemm_vivado/gemm_vivado.srcs/sources_1/bd/gemm/ip/gemm_axi_mem_intercon_imp_auto_pc_0/gemm_axi_mem_intercon_imp_auto_pc_0.xci
# IP: The module: 'gemm_axi_mem_intercon_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/darshith/hls/gemm/gemm_vivado/gemm_vivado.gen/sources_1/bd/gemm/ip/gemm_axi_mem_intercon_imp_auto_pc_0/gemm_axi_mem_intercon_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gemm_axi_mem_intercon_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
