# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/gemm/gemm.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm || ORIG_REF_NAME==gemm} -quiet] -quiet

# IP: bd/gemm/ip/gemm_processing_system7_0_0/gemm_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_processing_system7_0_0 || ORIG_REF_NAME==gemm_processing_system7_0_0} -quiet] -quiet

# IP: bd/gemm/ip/gemm_gemm_kernel_0_0/gemm_gemm_kernel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_gemm_kernel_0_0 || ORIG_REF_NAME==gemm_gemm_kernel_0_0} -quiet] -quiet

# IP: bd/gemm/ip/gemm_axi_smc_0/gemm_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_axi_smc_0 || ORIG_REF_NAME==gemm_axi_smc_0} -quiet] -quiet

# IP: bd/gemm/ip/gemm_rst_ps7_0_100M_0/gemm_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_rst_ps7_0_100M_0 || ORIG_REF_NAME==gemm_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/gemm/ip/gemm_axi_mem_intercon_0/gemm_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_axi_mem_intercon_0 || ORIG_REF_NAME==gemm_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/gemm/ip/gemm_axi_mem_intercon_1_0/gemm_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_axi_mem_intercon_1_0 || ORIG_REF_NAME==gemm_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/gemm/ip/gemm_axi_mem_intercon_2_0/gemm_axi_mem_intercon_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_axi_mem_intercon_2_0 || ORIG_REF_NAME==gemm_axi_mem_intercon_2_0} -quiet] -quiet

# IP: bd/gemm/ip/gemm_axi_mem_intercon_imp_auto_pc_0/gemm_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==gemm_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/gemm/ip/gemm_axi_mem_intercon_imp_auto_us_0/gemm_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==gemm_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/gemm/ip/gemm_axi_mem_intercon_1_imp_auto_pc_0/gemm_axi_mem_intercon_1_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_axi_mem_intercon_1_imp_auto_pc_0 || ORIG_REF_NAME==gemm_axi_mem_intercon_1_imp_auto_pc_0} -quiet] -quiet

# IP: bd/gemm/ip/gemm_axi_mem_intercon_1_imp_auto_us_0/gemm_axi_mem_intercon_1_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_axi_mem_intercon_1_imp_auto_us_0 || ORIG_REF_NAME==gemm_axi_mem_intercon_1_imp_auto_us_0} -quiet] -quiet

# IP: bd/gemm/ip/gemm_axi_mem_intercon_2_imp_auto_pc_0/gemm_axi_mem_intercon_2_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_axi_mem_intercon_2_imp_auto_pc_0 || ORIG_REF_NAME==gemm_axi_mem_intercon_2_imp_auto_pc_0} -quiet] -quiet

# IP: bd/gemm/ip/gemm_axi_mem_intercon_2_imp_auto_us_0/gemm_axi_mem_intercon_2_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gemm_axi_mem_intercon_2_imp_auto_us_0 || ORIG_REF_NAME==gemm_axi_mem_intercon_2_imp_auto_us_0} -quiet] -quiet

# XDC: /home/darshith/hls/gemm/gemm_vivado/gemm_vivado.gen/sources_1/bd/gemm/gemm_ooc.xdc
